version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: Installing dependencies
          command: npm install

      - run:
          name: ESLint
          command: npm run eslint

      - run:
          name: Stylelint
          command: npm run stylelint
        
      - run:
          name: Running tests
          command: npm run test

      - run:
          name: Building UI components
          command: npm run build
            
      - run:
          name: Build Styleguide
          command: npm run docs:build

      - run:
          name: Deploy styleguide
          command: |
            sudo apt-get -y -qq install awscli
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync $HUGO_BUILD_DIR \
              s3://your-bucket-name/your-subfolder --delete
            else
              echo "Not master branch, dry run only"
            fi


